version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: contacts_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d contacts_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: contacts_go_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: contacts_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: