CREATE TABLE IF NOT EXISTS contacts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL
    );

INSERT INTO contacts (name, phone) VALUES ('Tony Stark', '0995633740') ON CONFLICT DO NOTHING;